CREATE TABLE `alb_logs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`aws_profile` text NOT NULL,
	`type` text NOT NULL,
	`timestamp` text NOT NULL,
	`elb_name` text NOT NULL,
	`client_ip` text NOT NULL,
	`client_port` text NOT NULL,
	`target_ip` text,
	`target_port` text,
	`request_processing_time` real NOT NULL,
	`target_processing_time` real NOT NULL,
	`response_processing_time` real NOT NULL,
	`total_time` real NOT NULL,
	`elb_status_code` text NOT NULL,
	`target_status_code` text NOT NULL,
	`is_timeout` integer DEFAULT false NOT NULL,
	`is_rejected` integer DEFAULT false NOT NULL,
	`received_bytes` integer NOT NULL,
	`sent_bytes` integer NOT NULL,
	`request_method` text NOT NULL,
	`request_url` text NOT NULL,
	`request_path` text NOT NULL,
	`request_protocol` text NOT NULL,
	`user_agent` text,
	`ssl_cipher` text,
	`ssl_protocol` text,
	`target_group_arn` text,
	`trace_id` text,
	`domain_name` text,
	`raw_line` text NOT NULL
);
